/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jony
 */
public class FrmInicio extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form FrmInicio
     */
   public frmAlumno frmAlm=new frmAlumno();
   public FrmMatricula frmMatr=new FrmMatricula();
   public frmCurso frmCur=new frmCurso();
   public frmNotas frmN=new frmNotas();
    public FrmInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnAlumnos.addActionListener(this);
        btnMatricula.addActionListener(this);
        btnCursos.addActionListener(this);
        btnNotas.addActionListener(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumnos = new javax.swing.JButton();
        btnMatricula = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓN COLEGIO - INICIO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlumnos.setBackground(new java.awt.Color(153, 153, 153));
        btnAlumnos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, 70));

        btnMatricula.setBackground(new java.awt.Color(153, 153, 153));
        btnMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMatricula.setText("Matricula");
        getContentPane().add(btnMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 160, 70));

        btnNotas.setBackground(new java.awt.Color(153, 153, 153));
        btnNotas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNotas.setText("Notas");
        getContentPane().add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 70));

        btnCursos.setBackground(new java.awt.Color(153, 153, 153));
        btnCursos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCursos.setText("Cursos");
        getContentPane().add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 160, 70));

        lblFondo.setBackground(new java.awt.Color(153, 153, 153));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/degradados-wallpapers-3.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }
    
    //-----------------//
    
    public void llamadas(int x){
        switch(x){
            case 1:
               frmAlm.setVisible(true);
               this.dispose();
               break;
            case 2:
                frmMatr.setVisible(true);
                this.dispose();
                break;
            case 3:
                frmCur.setVisible(true);
                this.dispose();
                break;
            case 4:
                frmN.setVisible(true);
                this.dispose();
                break;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnNotas;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.btnAlumnos){
            llamadas(1);
        }
       if(e.getSource()==this.btnMatricula){
            llamadas(2);
        }
       if(e.getSource()==this.btnCursos){
            llamadas(3);
        }
       if(e.getSource()==this.btnNotas){
            llamadas(4);
        }
   }
}
