/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Cursos;
import Modelo.Matricula;
import Modelo.Notas;
import controlador.c_RegNotas;
import controlador.tools.Utilitarios;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jony
 */
public class frmNotasReg extends javax.swing.JFrame {

    /**
     * Creates new form frmNotasReg
     */
    Utilitarios util;
    c_RegNotas control;
    Matricula matri;

    Cursos Cur;

    public frmNotasReg() {
        initComponents();
        this.setLocationRelativeTo(null);
        util = new Utilitarios();
        control = new c_RegNotas();
        matri = new Matricula();
        tblAlumnos.setModel(modeloT_Alumnos());
        tblSituacion.setModel(modeloT_Situacion());
        cboN1.setModel(modeloNotas());
        cboN2.setModel(modeloNotas());
        cboN3.setModel(modeloNotas());
        cboN4.setModel(modeloNotas());
        cboN5.setModel(modeloNotas());
        cboN6.setModel(modeloNotas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ychAño = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        cboNivelA = new javax.swing.JComboBox<>();
        BtnVerAlumnos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboN1 = new javax.swing.JComboBox<>();
        cboN2 = new javax.swing.JComboBox<>();
        cboN3 = new javax.swing.JComboBox<>();
        cboN4 = new javax.swing.JComboBox<>();
        cboN5 = new javax.swing.JComboBox<>();
        cboN6 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSituacion = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblCantNotas = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        cboCurso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblCantAlumnos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GESTIÓN COLEGIO - NOTAS - Registrar");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Notas - Registrar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 320, 40));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Año");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nivel y Año");

        cboNivelA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1° Primaria", "2° Primaria", "3° Primaria", "4° Primaria", "5° Primaria", "6° Primaria", "1° Secundaria", "2° Secundaria", "3° Secundaria", "4° Secundaria", "5° Secundaria" }));
        cboNivelA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNivelAItemStateChanged(evt);
            }
        });

        BtnVerAlumnos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnVerAlumnos.setForeground(new java.awt.Color(0, 102, 153));
        BtnVerAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_group.png"))); // NOI18N
        BtnVerAlumnos.setText("Ver Alumnos");
        BtnVerAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ychAño, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboNivelA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BtnVerAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ychAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboNivelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(BtnVerAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 230));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAlumnos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblAlumnosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 630, 230));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nota 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Nota 2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nota 3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Nota 4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Nota 5");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nota 6");

        cboN1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboN2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboN3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboN4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboN5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboN6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblSituacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSituacion);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Curso");

        lblCurso.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(204, 204, 204));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 102, 153));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save (2).png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setOpaque(false);

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 102, 153));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_circle_double.png"))); // NOI18N
        btnModificar.setMnemonic('M');
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 102, 153));
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        btnOk.setMnemonic('O');
        btnOk.setText("OK");
        btnOk.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Notas Registradas");

        lblCantNotas.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblCantNotas.setForeground(new java.awt.Color(204, 204, 204));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 102, 153));
        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCursoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cursos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)))
                        .addComponent(lblCantNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(lblCurso))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cboN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cboN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cboN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(cboN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblCantNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 940, 340));

        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 50));

        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left1.png"))); // NOI18N
        btnAtras.setMnemonic('o');
        btnAtras.setText("Menú Notas");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 740, -1, 50));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Cantidad de alumnos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 100, -1));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/degradados-wallpapers-3.jpg"))); // NOI18N
        lblFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        lblCantAlumnos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblCantAlumnos.setForeground(new java.awt.Color(204, 204, 204));
        lblCantAlumnos.setText("jLabel14");
        getContentPane().add(lblCantAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        util.Salir();
    }//GEN-LAST:event_formWindowClosing

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        frmNotas n = new frmNotas();
        int x = JOptionPane.showConfirmDialog(null, "¿Deséa ir al menú notas?", "Menú", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            n.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (util.menuI()) {
            this.dispose();
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void BtnVerAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerAlumnosActionPerformed
        if (cboNivelA.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un grado de la lista");
        } else {
            DefaultTableModel modelo = modeloT_Alumnos();
            Object[] columna = new Object[3];
            List<Object[]> listAlumnos = control.listarAlumnos(getNivel(), String.valueOf(ychAño.getYear()));
            if (!listAlumnos.isEmpty()) {
                int nOrden = 1;
                for (Object[] datos : listAlumnos) {
                    columna[0] = nOrden;
                    columna[1] = (datos[1]);
                    columna[2] = (datos[2]);
                    modelo.addRow(columna);
                    nOrden++;
                }
                tblAlumnos.setModel(modelo);
                lblCantAlumnos.setText(String.valueOf(modelo.getRowCount()));
            } else {
                JOptionPane.showMessageDialog(null, "no hay alumnos matriculados en ese año o nivel");
            }
        }
    }//GEN-LAST:event_BtnVerAlumnosActionPerformed

    private void cboNivelAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNivelAItemStateChanged
        String nivel = getNivel();

        cboCurso.setModel(modeloCombo(nivel));

    }//GEN-LAST:event_cboNivelAItemStateChanged

    private void cboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCursoItemStateChanged
        if (cboCurso.getSelectedIndex() > 0) {
            lblCurso.setText(cboCurso.getSelectedItem().toString());
            btnRegistrar.setEnabled(true);
        }

    }//GEN-LAST:event_cboCursoItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        if (matri.getCodMatricula() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un alumno");

        } else {
            boolean r = false;
            int contReg = 0;
            Notas n = getDatos(matri);
            if (r = true) {//// el controlador va devolver true si registra las notas
                cboN1.setSelectedIndex(0);
                cboN2.setSelectedIndex(0);
                cboN3.setSelectedIndex(0);
                cboN4.setSelectedIndex(0);
                cboN5.setSelectedIndex(0);
                cboN6.setSelectedIndex(0);
                llenarTSituacion();
                contReg++;
            } else {
                JOptionPane.showMessageDialog(null, "NO se pudo registrar las notas para el alumno", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if (lblCantAlumnos.getText().equals(contReg)) {// si la cantidad de alumnos es igual a la de registros 
                btnRegistrar.setEnabled(false);//se desabilita el boton registrar
                btnNuevo.setEnabled(true);//se habilita el boton nuevo
                btnModificar.setEnabled(true);//se habilita el boton modificar

            }
            lblCantNotas.setText(String.valueOf(contReg));
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tblAlumnosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAlumnosFocusLost
        if (tblAlumnos.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Seleccione solo un alumno");
        } else {
            int nFila = tblAlumnos.getSelectedRow();
            matri.setCodMatricula((int) tblAlumnos.getValueAt(nFila, 0));
        }
    }//GEN-LAST:event_tblAlumnosFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        lblCantNotas.setText(null);
        btnRegistrar.setEnabled(true);
        tblSituacion.setModel(modeloT_Situacion());
        cboCurso.setSelectedIndex(0);
        matri.setCodMatricula(0);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        if(tblSituacion.getSelectedRowCount()>1){
         JOptionPane.showMessageDialog(null, "seleccione solo un alumno de la tabla");
        }else{
        int fila=tblSituacion.getSelectedRow();
         Notas n = new Notas();
         n.setIdNotas((int)(tblSituacion.getValueAt(fila, 0)));
         matri.setCodMatricula((int)(tblSituacion.getValueAt(fila, 1)));
         n.setMatricula(matri);
         //n.setCursos(Cur);
         n.setN1((int)(tblSituacion.getValueAt(fila, 2)));
         n.setN2((int)(tblSituacion.getValueAt(fila, 3)));
         n.setN3((int)(tblSituacion.getValueAt(fila, 4)));
         n.setN4((int)(tblSituacion.getValueAt(fila, 5)));
         n.setN5((int)(tblSituacion.getValueAt(fila, 6)));
         n.setN6((int)(tblSituacion.getValueAt(fila, 7)));
         n.setPromedio((double)(tblSituacion.getValueAt(fila, 8)));
         n.setSituacion(String.valueOf(tblSituacion.getValueAt(fila, 8)));
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNotasReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNotasReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNotasReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNotasReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNotasReg().setVisible(true);
            }
        });
    }
////****---------------metodos auxiliares------////////

    private DefaultComboBoxModel modeloNotas() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("00");
        modelo.addElement("01");
        modelo.addElement("02");
        modelo.addElement("03");
        modelo.addElement("04");
        modelo.addElement("05");
        modelo.addElement("06");
        modelo.addElement("07");
        modelo.addElement("08");
        modelo.addElement("09");
        modelo.addElement("10");
        modelo.addElement("11");
        modelo.addElement("12");
        modelo.addElement("13");
        modelo.addElement("14");
        modelo.addElement("15");
        modelo.addElement("16");
        modelo.addElement("17");
        modelo.addElement("18");
        modelo.addElement("19");
        modelo.addElement("20");
        return modelo;
    }

    private DefaultTableModel modeloT_Alumnos() {
        DefaultTableModel modeloT = new DefaultTableModel();
        modeloT.addColumn("N°");
        modeloT.addColumn("Alumno");
        modeloT.addColumn("Cod_Matricula");
        return modeloT;
    }

    private DefaultTableModel modeloT_Situacion() {
        DefaultTableModel modeloT = new DefaultTableModel();
        modeloT.addColumn("cod_reg");
        modeloT.addColumn("Codigo alumno");
        modeloT.addColumn("N1");
        modeloT.addColumn("N2");
        modeloT.addColumn("N3");
        modeloT.addColumn("N4");
        modeloT.addColumn("N5");
        modeloT.addColumn("N6");
        modeloT.addColumn("Situación");
        return modeloT;
    }

    private String getNivel() {
        String nivel = null;
        if (cboNivelA.getSelectedIndex() < 7) {
            nivel = "10" + cboNivelA.getSelectedIndex();
        } else {
            nivel = "20" + cboNivelA.getSelectedIndex();
        }
        return nivel;
    }

    private DefaultComboBoxModel modeloCombo(String codNivel) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        List<Object[]> lcombo = control.listarCursos(codNivel);
        if (lcombo.isEmpty()) {
            modelo.addElement("NO hay Cursos");
        } else {
            modelo.addElement("Seleccione");
            for (Object[] datos : lcombo) {
                modelo.addElement(datos[1]);
            }
        }

        return modelo;
    }

    private Notas getDatos(Matricula m) {
        Notas n = new Notas();
        int[] notas = new int[6];
        int acuNotas = 0;
        double prom = 0;
        n.setMatricula(m);
        //n.setCursos(cursos);
        notas[0] = cboN1.getSelectedIndex();
        notas[1] = cboN2.getSelectedIndex();
        notas[2] = cboN3.getSelectedIndex();
        notas[3] = cboN4.getSelectedIndex();
        notas[4] = cboN5.getSelectedIndex();
        notas[5] = cboN6.getSelectedIndex();
        //
        n.setN1(notas[0]);
        n.setN2(notas[1]);
        n.setN3(notas[2]);
        n.setN4(notas[3]);
        n.setN5(notas[4]);
        n.setN6(notas[5]);
        for (int i = 0; i < 6; i++) {
            acuNotas = +notas[i];
        }
        prom = Math.round(acuNotas / 6);
        n.setPromedio(prom);
        n.setSituacion((prom > 11) ? "Aprobado" : "Desaprobado");

        return n;
    }

    private void llenarTSituacion() {
        DefaultTableModel mts = modeloT_Situacion();
        Object[] columna = new Object[9];
        List<Object[]> listSituacion = control.verNotas((String.valueOf(ychAño.getYear())),lblCurso.getText(),getNivel());

        for (Object[] datos : listSituacion) {
            columna[0] = (datos[1]);
            columna[1] = (datos[2]);
            columna[2] = (datos[3]);
            columna[3] = (datos[4]);
            columna[4] = (datos[5]);
            columna[5] = (datos[6]);
            columna[6] = (datos[7]);
            columna[7] = (datos[8]);
            columna[8] = (datos[9]);
            mts.addColumn(columna);
        }
        tblSituacion.setModel(mts);
    }
    //*******--------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVerAlumnos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboN1;
    private javax.swing.JComboBox<String> cboN2;
    private javax.swing.JComboBox<String> cboN3;
    private javax.swing.JComboBox<String> cboN4;
    private javax.swing.JComboBox<String> cboN5;
    private javax.swing.JComboBox<String> cboN6;
    private javax.swing.JComboBox<String> cboNivelA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantAlumnos;
    private javax.swing.JLabel lblCantNotas;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTable tblSituacion;
    private com.toedter.calendar.JYearChooser ychAño;
    // End of variables declaration//GEN-END:variables
}
