package vista;

import javax.swing.DefaultComboBoxModel;
import controlador.tools.Utilitarios;

/**
 *
 * @author Jony
 */
public class frmVerNotas extends javax.swing.JFrame {

    Utilitarios util = new Utilitarios();

    /**
     * Creates new form frmVerNotas
     */
    public frmVerNotas() {
        initComponents();
        this.cboNivelgrado1.setModel(util.modeloNG());
        this.cboNivelGrado2.setModel(util.modeloNG());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoBusqueda = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        pnGradoCurso = new javax.swing.JPanel();
        rbtGradoAño = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ychAño = new com.toedter.calendar.JYearChooser();
        cboNivelgrado1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodAlumno = new javax.swing.JTextField();
        cboNivelGrado2 = new javax.swing.JComboBox<>();
        btnVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        btnInicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GESTION COLEGIO - NOTAS - Ver");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Notas - Ver Reportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 400, 50));

        pnGradoCurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnGradoCurso.setOpaque(false);

        bgTipoBusqueda.add(rbtGradoAño);
        rbtGradoAño.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtGradoAño.setForeground(new java.awt.Color(204, 204, 204));
        rbtGradoAño.setSelected(true);
        rbtGradoAño.setText("Por grado y año");
        rbtGradoAño.setOpaque(false);
        rbtGradoAño.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtGradoAñoStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Año");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nivel ygrado");

        cboCurso.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Curso");

        cboNivelgrado1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cboNivelgrado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnGradoCursoLayout = new javax.swing.GroupLayout(pnGradoCurso);
        pnGradoCurso.setLayout(pnGradoCursoLayout);
        pnGradoCursoLayout.setHorizontalGroup(
            pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGradoCursoLayout.createSequentialGroup()
                .addGroup(pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnGradoCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnGradoCursoLayout.createSequentialGroup()
                                .addComponent(rbtGradoAño)
                                .addGap(13, 13, 13))
                            .addGroup(pnGradoCursoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ychAño, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnGradoCursoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboNivelgrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        pnGradoCursoLayout.setVerticalGroup(
            pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGradoCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtGradoAño)
                .addGap(18, 18, 18)
                .addGroup(pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(cboNivelgrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ychAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnGradoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(pnGradoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 370, 170));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setOpaque(false);

        bgTipoBusqueda.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("Por Codigo de alumno y año de estudios");
        jRadioButton1.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nivel y grado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Codigo");

        txtCodAlumno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodAlumno.setToolTipText("Codigo del alumno (DNI)");
        txtCodAlumno.setEnabled(false);

        cboNivelGrado2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cboNivelGrado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNivelGrado2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNivelGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRadioButton1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtCodAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNivelGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 170));

        btnVer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVer.setForeground(new java.awt.Color(0, 102, 153));
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/150_glasses.png"))); // NOI18N
        btnVer.setMnemonic('e');
        btnVer.setText("Ver");
        btnVer.setToolTipText("Ver reporte segun los parametros selecionados");
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 170, 50));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 840, 310));

        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnInicio.setMnemonic('n');
        btnInicio.setText("INICIO");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 713, 130, 50));

        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left1.png"))); // NOI18N
        btnMenu.setMnemonic('o');
        btnMenu.setText("Menú notas");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 713, 190, 50));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(0, 102, 153));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/printer_blue.png"))); // NOI18N
        btnImprimir.setMnemonic('p');
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 170, 50));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/degradados-wallpapers-3.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtGradoAñoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtGradoAñoStateChanged
        if (rbtGradoAño.isSelected()) {
            ychAño.setEnabled(true);
            cboCurso.setEnabled(true);
            cboNivelgrado1.setEnabled(true);
            cboNivelGrado2.setEnabled(false);
            txtCodAlumno.setEditable(false);
        } else {
            ychAño.setEnabled(false);
            cboCurso.setEnabled(false);
            cboNivelgrado1.setEnabled(false);
            cboNivelGrado2.setEnabled(true);
            txtCodAlumno.setEditable(false);
        }
    }//GEN-LAST:event_rbtGradoAñoStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        util.Salir();
    }//GEN-LAST:event_formWindowClosing

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (util.menuI()) {
            this.dispose();
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        frmNotas n= new frmNotas();
        n.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVerNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVerNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVerNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVerNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVerNotas().setVisible(true);
            }
        });
    }
    ///------------------

    public DefaultComboBoxModel NivelyGrado() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Seleccione");
        modelo.addElement("1° Primaria");
        modelo.addElement("2° Primaria");
        modelo.addElement("3° Primaria");
        modelo.addElement("4° Primaria");
        modelo.addElement("5° Primaria");
        modelo.addElement("6° Primaria");
        modelo.addElement("1° Secundaria");
        modelo.addElement("2° Secundaria");
        modelo.addElement("3° Secundaria");
        modelo.addElement("4° Secundaria");
        modelo.addElement("5° Secundaria");

        return modelo;
    }

    ////---------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoBusqueda;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboNivelGrado2;
    private javax.swing.JComboBox<String> cboNivelgrado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPanel pnGradoCurso;
    private javax.swing.JRadioButton rbtGradoAño;
    private javax.swing.JTable tblReportes;
    private javax.swing.JTextField txtCodAlumno;
    private com.toedter.calendar.JYearChooser ychAño;
    // End of variables declaration//GEN-END:variables
}
