package Modelo;
// Generated 16/06/2017 06:14:45 PM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String codAlumno;
     private String nombres;
     private String apaterno;
     private String amaterno;
     private String estado;
     private Date fechaNac;
     private Set matriculas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(String codAlumno, String nombres, String apaterno, String amaterno, String estado, Date fechaNac) {
        this.codAlumno = codAlumno;
        this.nombres = nombres;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.estado = estado;
        this.fechaNac = fechaNac;
    }
    public Alumno(String codAlumno, String nombres, String apaterno, String amaterno, String estado, Date fechaNac, Set matriculas) {
       this.codAlumno = codAlumno;
       this.nombres = nombres;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.estado = estado;
       this.fechaNac = fechaNac;
       this.matriculas = matriculas;
    }
   
    public String getCodAlumno() {
        return this.codAlumno;
    }
    
    public void setCodAlumno(String codAlumno) {
        this.codAlumno = codAlumno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


