package Modelo;
// Generated 16/06/2017 06:14:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Integer codMatricula;
     private Alumno alumno;
     private Nivel nivel;
     private Date fechaMatricula;
     private Set notases = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(Alumno alumno, Nivel nivel, Date fechaMatricula) {
        this.alumno = alumno;
        this.nivel = nivel;
        this.fechaMatricula = fechaMatricula;
    }
    public Matricula(Alumno alumno, Nivel nivel, Date fechaMatricula, Set notases) {
       this.alumno = alumno;
       this.nivel = nivel;
       this.fechaMatricula = fechaMatricula;
       this.notases = notases;
    }
   
    public Integer getCodMatricula() {
        return this.codMatricula;
    }
    
    public void setCodMatricula(Integer codMatricula) {
        this.codMatricula = codMatricula;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


