package Modelo;
// Generated 16/06/2017 06:14:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nivel generated by hbm2java
 */
public class Nivel  implements java.io.Serializable {


     private String idNivel;
     private String nivel;
     private char grado;
     private Set matriculas = new HashSet(0);

    public Nivel() {
    }

	
    public Nivel(String idNivel, String nivel, char grado) {
        this.idNivel = idNivel;
        this.nivel = nivel;
        this.grado = grado;
    }
    public Nivel(String idNivel, String nivel, char grado, Set matriculas) {
       this.idNivel = idNivel;
       this.nivel = nivel;
       this.grado = grado;
       this.matriculas = matriculas;
    }
   
    public String getIdNivel() {
        return this.idNivel;
    }
    
    public void setIdNivel(String idNivel) {
        this.idNivel = idNivel;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public char getGrado() {
        return this.grado;
    }
    
    public void setGrado(char grado) {
        this.grado = grado;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


