package Modelo;
// Generated 26/05/2017 06:16:01 PM by Hibernate Tools 4.3.1



/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private Integer idNotas;
     private Cursos cursos;
     private Matricula matricula;
     private double n1;
     private double n2;
     private double n3;
     private double n4;
     private double n5;
     private double n6;
     private String situacion;

    public Notas() {
    }

    public Notas(Cursos cursos, Matricula matricula, double n1, double n2, double n3, double n4, double n5, double n6, String situacion) {
       this.cursos = cursos;
       this.matricula = matricula;
       this.n1 = n1;
       this.n2 = n2;
       this.n3 = n3;
       this.n4 = n4;
       this.n5 = n5;
       this.n6 = n6;
       this.situacion = situacion;
    }
   
    public Integer getIdNotas() {
        return this.idNotas;
    }
    
    public void setIdNotas(Integer idNotas) {
        this.idNotas = idNotas;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public double getN1() {
        return this.n1;
    }
    
    public void setN1(double n1) {
        this.n1 = n1;
    }
    public double getN2() {
        return this.n2;
    }
    
    public void setN2(double n2) {
        this.n2 = n2;
    }
    public double getN3() {
        return this.n3;
    }
    
    public void setN3(double n3) {
        this.n3 = n3;
    }
    public double getN4() {
        return this.n4;
    }
    
    public void setN4(double n4) {
        this.n4 = n4;
    }
    public double getN5() {
        return this.n5;
    }
    
    public void setN5(double n5) {
        this.n5 = n5;
    }
    public double getN6() {
        return this.n6;
    }
    
    public void setN6(double n6) {
        this.n6 = n6;
    }
    public String getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }




}


