package Modelo;
// Generated 16/06/2017 06:14:45 PM by Hibernate Tools 4.3.1



/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private Integer idNotas;
     private Cursos cursos;
     private Matricula matricula;
     private int n1;
     private int n2;
     private int n3;
     private int n4;
     private int n5;
     private int n6;
     private double promedio;
     private String situacion;

    public Notas() {
    }

    public Notas(Cursos cursos, Matricula matricula, int n1, int n2, int n3, int n4, int n5, int n6, double promedio, String situacion) {
       this.cursos = cursos;
       this.matricula = matricula;
       this.n1 = n1;
       this.n2 = n2;
       this.n3 = n3;
       this.n4 = n4;
       this.n5 = n5;
       this.n6 = n6;
       this.promedio = promedio;
       this.situacion = situacion;
    }
   
    public Integer getIdNotas() {
        return this.idNotas;
    }
    
    public void setIdNotas(Integer idNotas) {
        this.idNotas = idNotas;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public int getN1() {
        return this.n1;
    }
    
    public void setN1(int n1) {
        this.n1 = n1;
    }
    public int getN2() {
        return this.n2;
    }
    
    public void setN2(int n2) {
        this.n2 = n2;
    }
    public int getN3() {
        return this.n3;
    }
    
    public void setN3(int n3) {
        this.n3 = n3;
    }
    public int getN4() {
        return this.n4;
    }
    
    public void setN4(int n4) {
        this.n4 = n4;
    }
    public int getN5() {
        return this.n5;
    }
    
    public void setN5(int n5) {
        this.n5 = n5;
    }
    public int getN6() {
        return this.n6;
    }
    
    public void setN6(int n6) {
        this.n6 = n6;
    }
    public double getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(double promedio) {
        this.promedio = promedio;
    }
    public String getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }




}


